name: Release 3X-UI for Windows

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform:
          - amd64
        os:
          - windows-2019
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Setup Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.21'

      - name: Build x-ui
        run: |
          $env:CGO_ENABLED="1"
          $env:GOOS="windows"
          $env:GOARCH="${{ matrix.platform }}"
          go build -o xui-release -v main.go
          
          New-Item -ItemType Directory -Force -Path x-ui
          Move-Item -Path xui-release -Destination x-ui/
          Copy-Item -Path x-ui.service -Destination x-ui/
          Copy-Item -Path x-ui.sh -Destination x-ui/
          Rename-Item -Path x-ui/xui-release -NewName x-ui/x-ui
          New-Item -ItemType Directory -Force -Path x-ui/bin
          Set-Location -Path x-ui/bin
          
          # Download dependencies
          $Xray_URL="https://github.com/XTLS/Xray-core/releases/download/v1.8.7/"
          if (${{ matrix.platform }} -eq "amd64") {
            Invoke-WebRequest -Uri ${Xray_URL}Xray-windows-64.zip -OutFile Xray-windows-64.zip
            Expand-Archive -Path Xray-windows-64.zip -DestinationPath .
            Remove-Item -Path Xray-windows-64.zip
          }
          Remove-Item -Path geoip.dat, geosite.dat
          Invoke-WebRequest -Uri https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat -OutFile geoip.dat
          Invoke-WebRequest -Uri https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat -OutFile geosite.dat
          Invoke-WebRequest -Uri https://github.com/chocolate4u/Iran-v2ray-rules/releases/latest/download/geoip.dat -OutFile geoip_IR.dat
          
      - name: Package
        run: Compress-Archive -Path x-ui/* -DestinationPath x-ui-windows-${{ matrix.platform }}.tar.gz
        
      - name: Upload
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: x-ui-windows-${{ matrix.platform }}.tar.gz
          asset_name: x-ui-windows-${{ matrix.platform }}.tar.gz
          prerelease: true
          overwrite: true
