name: Compile and Package 3X-UI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          repository: 'MHSanaei/3x-ui'
          path: './3x-ui'

      - name: Setup Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.21'

      - name: Build 3X-UI
        run: |
          cd 3x-ui
          go build -o 3x-ui.exe -v main.go

      - name: Package
        run: |
          Compress-Archive -Path 3x-ui/* -DestinationPath 3x-ui.zip

      - name: Upload
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: 3x-ui.zip
          asset_name: 3x-ui.zip
          prerelease: true
          overwrite: true
